version: '3.7'

services:
  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: any
        delay: 5s
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.entrypoints=https"
        - "traefik.http.routers.portainer.rule=Host(`pr.{{ traefik_domain }}`)"
        - "traefik.http.routers.portainer.tls.certresolver=httpresolver"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
      - portainer

  agent:
    image: portainer/agent
    restart: always
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer


networks:
  traefik:
    external: true
  portainer:
    name: portainer
    driver: overlay
    attachable: true

volumes:
  portainer_data:
    external: true
