- hosts: all
  tasks:
    - name: Install docker packages
      apt:
        pkg: [ 'apt-transport-https','ca-certificates', 'gnupg-agent', 'curl', 'software-properties-common', 'bash-completion' ]
        update_cache: yes
    - name: Add Docker s GPG key for ubuntu from official site
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Configure Docker for ubuntu stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
    - name: Update apt packages
      apt:
        update_cache: yes
    - name: Install docker-ce
      apt:
        pkg: [ 'docker-ce', 'docker-ce-cli', 'containerd.io' ]
        state: present
    - name: Install docker-compose from official github repo
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x,o+x'
    - name: Install docker-compose bash completion
      get_url:
        url: https://raw.githubusercontent.com/docker/compose/1.24.0/contrib/completion/bash/docker-compose
        dest: /etc/bash_completion.d/docker-compose
