- hosts: all
  tasks:
    - name: Install python packages
      apt:
        pkg: [ 'python3', 'python3-full', 'python3-pip' ]
        state: present

    - name: Install 'docker' pip module
      command: /usr/bin/pip3 install docker --break-system-packages

    - name: Install 'jsondiff' pip module
      command: /usr/bin/pip3 install jsondiff --break-system-packages
