- hosts: all
  tasks:
    - name: Install python pip
      apt: name=python3-pip state=latest

    - name: Install 'docker' pip module
      pip:
        name: docker

    - name: Install 'jsondiff' pip module
      pip:
        name: jsondiff
